### PR TITLE
Bugfix/improve move file to folder

### PR DESCRIPTION
**Pull request by Jesus1124**
- Move file by using side bar cut, paste. Using Move, Paste button.
- Move multi files using key, Control+X, Control+V.
- Move file using Drag and Drop.

### CODE REVIEW

**Comment by Jesus1124** [comment]
@Jesus1124 @supermavens  I hope you are doing well. 
Please reveiw my PR if you have time.: https://github.com/opacity/web2.0/pull/293
https://github.com/opacity/web2.0/pull/294

**Comment by kamranpirwani** [comment]
@Jesus1124 Could you outline the changes here on a product levels so we can review and also test end to end?

**Comment by Jesus1124** [comment]
@kamranpirwani Yes, sure.

**Comment by kamranpirwani** [comment]
@Jesus1124 Let me know when the PR description has been updated and I can give it a review

**Comment by kamranpirwani** [comment]
https://www.loom.com/share/40e5bfb5b2044e799fc272c1beae92ab

**Comment by Jesus1124** [comment]
@kamranpirwani Please share me details of your feedback.

**Comment by faizan-firekamp** [comment]
Features working properly

- Move file by using side bar cut, paste. Using Move, Paste button.

Features with bug

- Move multi files using key, Control+X, Control+V.
- Move file using Drag and Drop.

Moving file with ctl+x, ctrl+v

When we are trying to move a file using shortcut the file is not moved to the specific folder, it seems that the file is not being copied properly

Move file using Drag and Drop.

Whenever we are dragging a file if that file is hovered over a folder it automatically gets dropped without even dropping, so we need to change behaviour from hover to drop

@Jesus1124 please let me know if the comment and loom video is clear

**Pull request closed without merging**
